### ISSUE TITLE
twerking/crouching in the nether results in crash

### ISSUE THREAD

**Issue by JabSparrowtheoriginal** [Crypt1-C/Encrypted_-Modpack#52] opened 2022-08-08 06:57 UTC
holding down shift to creep to the edge of a cliff to see whats below has crashed my game twice so far in the nether

**Comment by JabSparrowtheoriginal** [comment] 2022-08-08 08:12
think its only in a specific biome where the netherrack is covered with the grass stuff, hasn't done it on this visit

**Comment by Premieress** [comment] 2022-08-08 19:18
which version of the modpack are you using?

**Comment by Sedus** [comment] 2022-08-09 14:13
![image](https://user-images.githubusercontent.com/76965026/183671497-64fe1fa7-a18a-4ff2-acff-6456a5cede81.png)

This biome?

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 16:28
I haven't crashed since the last update, but yeah seems like the biome...

**Comment by Sedus** [comment] 2022-08-09 16:32
I tried with older versions and no crash at all

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 18:21
nope not fixed, found the spot again...i'm attaching a screenshot. Soon as
I crouch...crash in the biome below and looking at the lava for some
reason. I'm using R-1.3 now. Incidentally Everytime I exit the modpack it
throws error messages but I dont know if that's related or not, but it
might be so its why I'm mentioning it. Perhaps a clean install of the pack
might clear it up if it's not reproducible.  if i crouch right here
guaranteed crash and even when not looking at the lava this time. I turned
around and crouched with the same result with my back to the lava. The
error code that pops up after I mentioned happens every time has an error
code of -1 but I've seen different codes as well. I tried uploading
screenshots but it was too large of file. so I uploaded it to gyazo an
online screenshotting program. I hope the link works.

https://gyazo.com/ea28b5b28a3bc0dfcca6777fa9c48e4f

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 18:37
Am attaching a smaller version of the screenshot in case that link doesn't
work for you just in case.

**Comment by Sedus** [comment] 2022-08-09 18:46
Tried the same biome and nothing

**Comment by Sedus** [comment] 2022-08-09 18:47
Can you tell your seed?

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 18:55
LostinPockets is the name of my save the seed is [-116941886856065958] I
tried doing a fresh install of the pack and it let me crouch a couple times
but on the third it crashed yet again.

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 18:56
[image: image.png]

**Comment by Sedus** [comment] 2022-08-09 19:01
You mean third crouch?

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:04
yes the third crouch resulted in the same crash

**Comment by Sedus** [comment] 2022-08-09 19:05
With same world? Playing on server or solo?

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:06
same world, solo

**Comment by Sedus** [comment] 2022-08-09 19:09
Hmmm somehow I crashed

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:11
yeah that was my thought too after the first time...I'm on a high end
gaming rig, 64 gigs of ram with 8 dedicated to modded minecraft. I don't
normally crash

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:12
wonder if its the twerking mod, what if we disable it in the nether...that
might clear up the crashing

**Comment by Sedus** [comment] 2022-08-09 19:13
Or Oh The Biomes You'll Go older version

**Comment by Sedus** [comment] 2022-08-09 19:15
Is this only reproducible when standing on grass stuff right?

**Comment by Sedus** [comment] 2022-08-09 19:17
crash report says: Description: Ticking player

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:18
Yeah. and so far just in that biome. I'm flying around in a previous save
to see if i can find the biome and see if it happens across saves

**Comment by Sedus** [comment] 2022-08-09 19:18
Caused by: java.lang.IllegalArgumentException: Cannot set property EnumProperty{name=half, clazz=class net.minecraft.world.level.block.state.properties.DoubleBlockHalf, values=[upper, lower]} as it does not exist in Block{byg:embur_roots}

**Comment by Sedus** [comment] 2022-08-09 19:20
https://github.com/AOCAWOL/BYG/issues/870

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:23
Yeah. in the Crimson Gardens on the overgrown crimson blackstone. I flew
around in creative on a previous save but couldn't find the crimson gardens
but did try twerking in various locations with no crashes

**Comment by Sedus** [comment] 2022-08-09 19:24
Well, we successfully found a previously reported issue.

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:25
Incidently I twerked outside the biome on the frozen white stuff forgot its
name. Like one block outside the Crimson Gardens standing on a different
block and it let me twerk like 20 times. Soon as i stepped onto the
overground crimson blackstone and twerked, it resulted in a crash
immediately.

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:29
oops...sorry about that. I did look but was hard to search for my issue
specifically as I didn't know exactly what was causing it at first

**Comment by Sedus** [comment] 2022-08-09 19:31
Some conflict between Oh The Biomes You'll Go and the twerking mod.

**Comment by JabSparrowtheoriginal** [comment] 2022-08-09 19:38
Do you need anything else from me? i'm getting ready to go afk for while

**Comment by Sedus** [comment] 2022-08-09 19:44
I'm just a regular player, I think Oh The Biomes You'll Go, mod developers can fix that I don't know.

**Comment by Sedus** [comment] 2022-08-09 19:48
ooorrrr we can just blacklist these plants in config

**Comment by Sedus** [comment] 2022-08-09 20:20
Solution: Add "byg:embur_roots" item to blacklist in twerk-config.toml
Also add: "byg:thereal_bellflower" "byg:ether_bush" "byg:ether_phylium" "byg:ether_grass".

**Comment by Sedus** [comment] 2022-08-09 21:28
you can blacklist entire mods by adding
"modid"

to the blacklist list inside the config file

I tried with "byg" and no crash.

**Comment by Reshy** [comment] 2022-08-10 10:25
> Solution: Add "byg:embur_roots" item to blacklist in twerk-config.toml Also add: "byg:thereal_bellflower" "byg:ether_bush" "byg:ether_phylium" "byg:ether_grass".

Reported this before, still hasn't been fixed sadly.

**Comment by Sedus** [comment] 2022-08-10 10:39
The problem is twerk-config.toml is for the TwerkItMeal mod.
Encrypted_ uses Squatgrow which has also a blacklist feature but can't blacklist a whole mod by ID. (squatgrow-common.toml)

I can suggest for everyone to delete Squatgrow mod and install TwerkItMeal after that just type "byg" to blacklist line in twerk-config.toml.

Modifying twerk-config.toml without TwerkItMeal being installed changes nothing.

**Comment by Reshy** [comment] 2022-08-10 12:11
> The problem is twerk-config.toml is for the TwerkItMeal mod. Encrypted_ uses Squatgrow which has also a blacklist feature but can't blacklist a whole mod by ID. (squatgrow-common.toml)
> 
> I can suggest for everyone to delete Squatgrow mod and install TwerkItMeal after that just type "byg" to blacklist line in twerk-config.toml.
> 
> Modifying twerk-config.toml without TwerkItMeal being installed changes nothing.

This problem happens with all "growing" mods, not just this one.

**Comment by Sedus** [comment] 2022-08-10 12:29
True.

At least we have a quick stable fix for this issue.

**Comment by JabSparrowtheoriginal** [comment] 2022-08-10 13:29
can't you just black list the nether all together? I dont know anything
about the mods or what the configs can do

**Comment by Sedus** [comment] 2022-08-10 13:54
I don't think you can block dimensions but I'm pretty sure you will be fine if you blacklist BYG with TwerkItMeal.

**Comment by 3733WOLF** [comment] 2022-08-10 14:16
That would also make it so we can't twerk the trees from that mod as well though, so I hope he keeps that in mind

**Comment by Sedus** [comment] 2022-08-10 14:21
Which BYG tree do you want to twerk?

**Comment by JabSparrowtheoriginal** [comment] 2022-08-10 15:31
its so odd, I'm on a new save new world new seed...same biome am twerking all day no crashes, lol twerk 3 more times and crashed oops

**Comment by Sedus** [comment] 2022-08-10 15:37
In Crimson Gardens biome only embur roots crash.

**Closed as completed** 2022-08-10 18:10 UTC
